### ISSUE TITLE
autobuilder.py hangs

### ISSUE THREAD

**Issue by julesfowler** [spacetelescope/training-library#10]
As I'm editing the `python` section of the training docs I had the issue that following the `editing_these_documents.txt` instructions for simpler workflow (lines 39-46), running the `autobuilder.py` hangs and no longer does what it's supposed to. 

This seems like an awesome idea for ease of doc edits if someone has the time/inclination to restore it.
(Or perhaps I'm the only one with this issue?)

**Comment by jwhite3** [comment]
This is related to #6

**Comment by laurenmarietta** [comment]
I also had this problem - it's not just you, @julesfowler !

**Comment by jwhite3** [comment]
I investigated this a little bit and for some reason on completion of this step:
```python
# Do an initial build, and open a browser window
    build_docs(target='riadocs')
```
the subprocess somehow gets caught in a loop. The next step would be to take a look at the subprocess: 

```python
def build_docs(target='html'):
    print('Building target "{}"...'.format(target))
    proc = subprocess.Popen(['make', target], stdout=subprocess.PIPE,
                            bufsize=1, cwd=PROJECT_DIR)
    buf = []
    for line in iter(proc.stdout.readline, ''):
        buf.append(line)
        # print(line, end='')  # uncomment this to enable output
    proc.stdout.close()
    returncode = proc.wait()
    if returncode != 0:
        print('*'*72)
        print('make exited with returncode != 0 (was {})'.format(returncode))
        print('*'*72)
        print('\n'.join(buf))
        print('*'*72)
    print('Build completed.')
```

**Comment by jwhite3** [comment]
We likely need to add something along the lines of: 

```python
cmd = silex.split('make {}'.format(target))

with subprocess.Popen(cmd, stdout=subprocess.PIPE) as p:
        while p.poll() is None:
            out = p.stderr.readline().decode('utf-8')
            if out == '' and p.poll() is not None:
                break
            if out:
                print(out)
```

instead of the stdout handling that we currently use. This should be easy to check and test, but I have meetings to go to ;)
@julesfowler @laurenmarietta want to give it a shot?

**Comment by jwhite3** [comment]
#12
