### ISSUE TITLE
Add astroquery to MAST training?

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/training-library#20]
Perusing to MAST training documentation, I wonder if we should add a section about using `astroquery` to programmatically access the archive? @jwhite3 what do you think?

**Comment by jwhite3** [comment]
This is a great idea

**Comment by jwhite3** [comment]
Assigned to @tddesjardins since he said he was taking it (?.. if I remember correctly, he said he was going to fold it into MAST updates? It's been a while since we talked, but I didn't want to lose track)

**Comment by jwhite3** [comment]
#37
