### ISSUE TITLE
Pysynphot sections in main index should be grouped together

### ISSUE THREAD

**Issue by jwhite3** [spacetelescope/training-library#23]
It looks like the Pysynphot training has been broken into for subsections: `Using Pysynphot`, `HST Conclusion`,  `JWST..`, and `Conclusion`

I think that these subsections are a good idea, but I don't think they should be broken up in the main index. Perhaps we could change this structure so that `Using Pysynphot` is converted to a folder that has the different subsections (notebooks) inside of it with the main index referencing the `Pysynphot` index (much like what Python or Spectroscopy have done).

**Comment by tddesjardins** [comment]
That's a reasonable suggestion. The only downside is a little more discussion at the end of each notebook to explain what to do next. I'll split it out when I work on #19 as well.

**Comment by jwhite3** [comment]
Sounds good! This is definitely lower on the priority list, so no worries

**Comment by tddesjardins** [comment]
@jwhite3 Thinking more on this, I think we might as well leave the PySynphot document as one notebook with the message on the top saying that PySynphot is no longer updated etc. and you should use STSynphot (cf. #19 ). Then the STSynphot notebooks could be split up like this. What do you think?

**Comment by jwhite3** [comment]
Sounds good to me! Thanks!

**Comment by tddesjardins** [comment]
Upon further thought, I'm not sure how this would work. The reason it's being broken up seems to do with the use of sections in the jupyter markdown, and the sphinx notebook converter is interpreting that as sectioning for the rst stuff. But if we split it into different notebooks in a folder, I'm not sure how it would interpret that. Would it try to merge them together into one document? I feel like we'd be left with a choice of do we have a single merged document that flows well (and thus notebooks that don't necessarily make as much sense as standalone documents), or notebooks that make sense and a merged document that gets repetitive.

**Comment by jwhite3** [comment]
#42
