### ISSUE TITLE
Publishing github pages

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/training-library#6]
Me again... In the previous version of this repository, there was a branch called "gh-pages" specifically for publishing pages. You could then enter `make gh-pages` if you were on master (with no uncommited changes) to publish the new edits to the webpage. Is this how you would like us to do that in this repository, as well? I don't see that branch here.

**Comment by jwhite3** [comment]
so make gh-pages actually creates the gh-pages branch for you! The reason this repo doesn't have that branch is because we haven't updated the webpage from this repository yet.

**Comment by aliciacanipe** [comment]
Oh okay. I was getting an error when I was trying build them using `make gh-pages`, and I thought maybe it was because it couldn't find the branch. I guess not. Have you ever gotten this error (below)? It seems to go all the way through building the pages and then fails when it's trying to switch to the gh-pages branch. 

`Output written on training.pdf (29 pages, 1227874 bytes).
Transcript written on training.log.
# Copy Spectroscopy training into pdf_guides
cp latexdocs/spectroscopy/training.pdf source/downloads/pdf_guides/spectroscopy_training.pdf
#
#
# Execute the Sphinx build
make html
make[2]: Entering directory '/Users/acanipe/Desktop/computer_setup_edits/training-library'
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.7.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] spectroscopy/index                                                                                                                            
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/acanipe/Desktop/computer_setup_edits/training-library/source/spectroscopy.txt: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] spectroscopy/index                                                                                                                             
generating indices... genindex
writing additional pages... search
copying downloadable files... [100%] downloads/pdf_guides/pyraf_training.pdf                                                                                            
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warnings.

The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.
make[2]: Leaving directory '/Users/acanipe/Desktop/computer_setup_edits/training-library'
make[1]: Leaving directory '/Users/acanipe/Desktop/computer_setup_edits/training-library'
git diff --exit-code
git diff --cached --exit-code
git checkout gh-pages
error: pathspec 'gh-pages' did not match any file(s) known to git.
make: *** [Makefile:97: gh-pages] Error 1`

**Comment by aliciacanipe** [comment]
Oops, GitHub translated some of the error message I just pasted into big headings... 
![make_ghpages_error](https://user-images.githubusercontent.com/18013408/41436913-20c85b70-6ff1-11e8-977a-e08197a7dcbe.png)

**Comment by jwhite3** [comment]
Hmm, well I guess I'm not correct in that! I guess the code assumes that there's a repo called `gh-pages`. Try creating a branch called `gh-pages` and then running it.

**Comment by aliciacanipe** [comment]
Okay, I created the branch and reran it. It didn't crash this time. I'll check in a little while to make sure that the changes actually got published. Thanks!!

**Comment by jwhite3** [comment]
Nailed it!

**Comment by aliciacanipe** [comment]
Well, I still see the old pages when I go to the link. So it didn't crash, but it also didn't update the pages. Have you been able to update them (or anyone else)? I'm not sure how to debug.

**Comment by jwhite3** [comment]
So it looks like your changes made it into the master branch, but not the gh-pages branch. try running a `git pull` then execute `make gh-pages`

**Comment by aliciacanipe** [comment]
Yeah, I've been wrestling with it today. Now it crashes while it's building the pages (after trying to build the version control pages): 

`The HTML pages are in build/html.

Build finished. The HTML pages are in build/html.
make[1]: Leaving directory '/Users/acanipe/Desktop/computer_setup_edits/training-library'
mv -fv build/html/* ./
build/html/_downloads -> ./_downloads
build/html/_images -> ./_images
build/html/_sources -> ./_sources
build/html/_static -> ./_static
build/html/apt_etc -> ./apt_etc
build/html/archives.html -> ./archives.html
build/html/boneyard.html -> ./boneyard.html
build/html/computer_setup.html -> ./computer_setup.html
build/html/drizzle.html -> ./drizzle.html
build/html/editing_these_documents.html -> ./editing_these_documents.html
build/html/genindex.html -> ./genindex.html
build/html/index.html -> ./index.html
build/html/ir_detector_course.html -> ./ir_detector_course.html
build/html/jwst_intro.html -> ./jwst_intro.html
build/html/jwst_read_modes.html -> ./jwst_read_modes.html
build/html/jwst_reference_output.html -> ./jwst_reference_output.html
build/html/jwst_telescopes_project.html -> ./jwst_telescopes_project.html
build/html/jwst_training.html -> ./jwst_training.html
build/html/objects.inv -> ./objects.inv
build/html/photometry.html -> ./photometry.html
build/html/pyraf.html -> ./pyraf.html
build/html/pysynphot.html -> ./pysynphot.html
build/html/python -> ./python
build/html/search.html -> ./search.html
build/html/searchindex.js -> ./searchindex.js
mv: rename build/html/spectroscopy to ./spectroscopy: Directory not empty
build/html/trainees.html -> ./trainees.html
build/html/tricks.html -> ./tricks.html
build/html/up_the_ramp_calwf3.html -> ./up_the_ramp_calwf3.html
build/html/using_idl.html -> ./using_idl.html
build/html/version_control.html -> ./version_control.html
make: *** [Makefile:103: gh-pages] Error 1`

I'll keep working on it and update you if I can get it to work at any point. Sorry!!

**Comment by jwhite3** [comment]
did you run `make riadocs` before `make gh-pages`?

**Comment by jwhite3** [comment]
Also no worries on this debugging process. It happens!

**Comment by aliciacanipe** [comment]
Yeah, I still get the same error above after running `make riadocs` before `make gh-pages`.

**Comment by jwhite3** [comment]
I think the issue is with the spectroscopy folder

**Comment by aliciacanipe** [comment]
It does seem to be having issues with the spectroscopy module but I don't know enough about the `make riadocs` or `make gh-pages` process to pinpoint the issue exactly. This is the message: 

![image](https://user-images.githubusercontent.com/18013408/41482234-f47a062e-70a2-11e8-8129-d11867cf1fc4.png)

And I don't see "spectroscopy.txt" in the source folder. Why is it looking for that?

**Comment by jwhite3** [comment]
Spectroscopy changed from a single file to a folder at some point. That's what's causing the move issue. 
In terms of it looking for a specific file, that'll require some digging into Makefile

**Comment by jwhite3** [comment]
#11
